-- supabase-staging.ddl — snapshot-contract of the Modo Nube staging schema (project fostjbbwstyuunmmefuk).
-- Generated by qa/cloud/dump-schema.sh from the live schema. Offline mold cross-checked by
-- CloudCapabilityManifestParityTests (manifest <-> this snapshot). Append-only; regenerate on any schema change.
-- Every syncable table also has: CREATE INDEX (user_id, server_seq); BEFORE INSERT OR UPDATE trigger stamp_server_seq();
--   ENABLE ROW LEVEL SECURITY + 4 per-command policies USING/WITH CHECK ((select auth.uid()) = user_id);
--   GRANT SELECT,INSERT,UPDATE TO authenticated; REVOKE DELETE FROM authenticated, anon (tombstone = UPDATE deleted=true).

-- ============ per-user server_seq axis (E2E-S3+S4) ============
CREATE TABLE sync_seq_counters (user_id UUID PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE, seq BIGINT NOT NULL DEFAULT 0);
CREATE FUNCTION stamp_server_seq() RETURNS trigger LANGUAGE plpgsql SECURITY DEFINER SET search_path = public AS $$
BEGIN INSERT INTO sync_seq_counters (user_id, seq) VALUES (NEW.user_id, 1)
  ON CONFLICT (user_id) DO UPDATE SET seq = sync_seq_counters.seq + 1 RETURNING seq INTO NEW.server_seq; RETURN NEW; END; $$;

-- ============ 16 domain entities ============
CREATE TABLE accounts (
  user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  sync_id UUID NOT NULL,
  name TEXT,
  currency_code TEXT,
  color_hex TEXT,
  icon_name TEXT,
  type TEXT,
  account_number TEXT,
  adjustment_mode TEXT,
  exclude_from_statistics BOOLEAN,
  is_archived BOOLEAN,
  is_system_account BOOLEAN,
  credit_card_payment_reminder BOOLEAN,
  credit_card_payment_day INTEGER,
  field_hlcs JSONB,
  hlc TEXT NOT NULL,
  deleted BOOLEAN NOT NULL DEFAULT false,
  deleted_hlc TEXT,
  server_seq BIGINT NOT NULL,
  schema_version INTEGER NOT NULL DEFAULT 1,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  PRIMARY KEY (user_id, sync_id)
);

CREATE TABLE budgets (
  user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  sync_id UUID NOT NULL,
  name TEXT,
  currency_code TEXT,
  limit_amount NUMERIC(18,4),
  category_id UUID,
  period_type TEXT,
  start_date TIMESTAMPTZ,
  end_date TIMESTAMPTZ,
  natures TEXT[],
  subcategory_ids UUID[],
  account_ids UUID[],
  tag_refs UUID[],
  is_active BOOLEAN,
  created_at TIMESTAMPTZ,
  is_favorite BOOLEAN,
  favorite_order INTEGER,
  alert_enabled BOOLEAN,
  alert_thresholds TEXT[],
  include_shared_expenses BOOLEAN,
  field_hlcs JSONB,
  hlc TEXT NOT NULL,
  deleted BOOLEAN NOT NULL DEFAULT false,
  deleted_hlc TEXT,
  server_seq BIGINT NOT NULL,
  schema_version INTEGER NOT NULL DEFAULT 1,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  PRIMARY KEY (user_id, sync_id)
);

CREATE TABLE cashflow_lines (
  user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  sync_id UUID NOT NULL,
  name TEXT,
  is_income BOOLEAN,
  sort_order INTEGER,
  is_enabled BOOLEAN,
  estimation_method TEXT,
  manual_amount NUMERIC(18,4),
  custom_months_raw TEXT[],
  category_ref UUID,
  subcategory_ref UUID,
  scheduled_payment_ref UUID,
  plan_ref UUID,
  field_hlcs JSONB,
  hlc TEXT NOT NULL,
  deleted BOOLEAN NOT NULL DEFAULT false,
  deleted_hlc TEXT,
  server_seq BIGINT NOT NULL,
  schema_version INTEGER NOT NULL DEFAULT 1,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  PRIMARY KEY (user_id, sync_id)
);

CREATE TABLE cashflow_overrides (
  user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  sync_id UUID NOT NULL,
  month_key TEXT,
  amount NUMERIC(18,4),
  note TEXT,
  line_ref UUID,
  field_hlcs JSONB,
  hlc TEXT NOT NULL,
  deleted BOOLEAN NOT NULL DEFAULT false,
  deleted_hlc TEXT,
  server_seq BIGINT NOT NULL,
  schema_version INTEGER NOT NULL DEFAULT 1,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  PRIMARY KEY (user_id, sync_id)
);

CREATE TABLE cashflow_plans (
  user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  sync_id UUID NOT NULL,
  name TEXT,
  starting_balance NUMERIC(18,4),
  default_months_ahead INTEGER,
  default_months_back INTEGER,
  show_other_expenses BOOLEAN,
  show_accumulated_balance BOOLEAN,
  starting_balance_date TIMESTAMPTZ,
  created_at TIMESTAMPTZ,
  updated_at_domain TIMESTAMPTZ,
  field_hlcs JSONB,
  hlc TEXT NOT NULL,
  deleted BOOLEAN NOT NULL DEFAULT false,
  deleted_hlc TEXT,
  server_seq BIGINT NOT NULL,
  schema_version INTEGER NOT NULL DEFAULT 1,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  PRIMARY KEY (user_id, sync_id)
);

CREATE TABLE categories (
  user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  sync_id UUID NOT NULL,
  name TEXT,
  color_hex TEXT,
  is_income BOOLEAN,
  is_default_seed BOOLEAN,
  is_visible BOOLEAN,
  sort_order INTEGER,
  icon_name TEXT,
  is_system BOOLEAN,
  field_hlcs JSONB,
  hlc TEXT NOT NULL,
  deleted BOOLEAN NOT NULL DEFAULT false,
  deleted_hlc TEXT,
  server_seq BIGINT NOT NULL,
  schema_version INTEGER NOT NULL DEFAULT 1,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  PRIMARY KEY (user_id, sync_id)
);

CREATE TABLE exchange_rates (
  user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  sync_id UUID NOT NULL,
  date_key TEXT,
  base TEXT,
  rates JSONB,
  timestamp TIMESTAMPTZ,                            -- [i5_fix] instante en que la tasa fue registrada por la API (modelo entero D, A3); canon c1 iso8601_ms_utc
  field_hlcs JSONB,
  hlc TEXT NOT NULL,
  deleted BOOLEAN NOT NULL DEFAULT false,
  deleted_hlc TEXT,
  server_seq BIGINT NOT NULL,
  schema_version INTEGER NOT NULL DEFAULT 1,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  PRIMARY KEY (user_id, sync_id)
);

CREATE TABLE favorite_payments (
  user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  sync_id UUID NOT NULL,
  name TEXT,
  transaction_type TEXT,
  amount NUMERIC(18,4),
  note TEXT,
  account_ref UUID,
  subcategory_ref UUID,
  tag_refs UUID[],
  need_override TEXT,
  currency_code TEXT,
  created_at TIMESTAMPTZ,
  display_order INTEGER,
  field_hlcs JSONB,
  hlc TEXT NOT NULL,
  deleted BOOLEAN NOT NULL DEFAULT false,
  deleted_hlc TEXT,
  server_seq BIGINT NOT NULL,
  schema_version INTEGER NOT NULL DEFAULT 1,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  PRIMARY KEY (user_id, sync_id)
);

CREATE TABLE group_bridge_prefs (
  user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  sync_id UUID NOT NULL,
  group_zone_id TEXT,
  bridge_override BOOLEAN,
  created_at TIMESTAMPTZ,
  field_hlcs JSONB,
  hlc TEXT NOT NULL,
  deleted BOOLEAN NOT NULL DEFAULT false,
  deleted_hlc TEXT,
  server_seq BIGINT NOT NULL,
  schema_version INTEGER NOT NULL DEFAULT 1,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  PRIMARY KEY (user_id, sync_id)
);

CREATE TABLE inbox_drafts (
  user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  sync_id UUID NOT NULL,
  note TEXT,
  amount NUMERIC(18,4),
  date TIMESTAMPTZ,
  account_ref UUID,
  subcategory_ref UUID,
  tag_refs UUID[],
  approved_transaction_ref UUID,
  source_type_raw TEXT,
  raw_text TEXT,
  evidence TEXT,
  confidence_amount TEXT,
  confidence_date TEXT,
  confidence_merchant TEXT,
  confidence_subcategory TEXT,
  needs_user_input TEXT[],
  newly_created_tag_names TEXT[],
  status_raw TEXT,
  cached_account_name TEXT,
  cached_subcategory_name TEXT,
  cached_category_color_hex TEXT,
  cached_subcategory_icon TEXT,
  cached_currency_code TEXT,
  source_scheduled_payment_ref UUID,
  split_expense_id TEXT,
  split_group_zone_id TEXT,
  split_settlement_id TEXT,
  opt_in_personal_only BOOLEAN,
  origin_reason_key TEXT,
  origin_actor_name TEXT,
  origin_group_name TEXT,
  created_at TIMESTAMPTZ,
  updated_at_domain TIMESTAMPTZ,
  field_hlcs JSONB,
  hlc TEXT NOT NULL,
  deleted BOOLEAN NOT NULL DEFAULT false,
  deleted_hlc TEXT,
  server_seq BIGINT NOT NULL,
  schema_version INTEGER NOT NULL DEFAULT 1,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  PRIMARY KEY (user_id, sync_id)
);

CREATE TABLE merchant_memory (
  user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  sync_id UUID NOT NULL,
  merchant_canonical TEXT,
  subcategory_ref UUID,
  count_approved INTEGER,
  count_corrected INTEGER,
  last_approved_at TIMESTAMPTZ,
  aliases TEXT[],
  field_hlcs JSONB,
  hlc TEXT NOT NULL,
  deleted BOOLEAN NOT NULL DEFAULT false,
  deleted_hlc TEXT,
  server_seq BIGINT NOT NULL,
  schema_version INTEGER NOT NULL DEFAULT 1,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  PRIMARY KEY (user_id, sync_id)
);

CREATE TABLE notification_items (
  user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  sync_id UUID NOT NULL,
  name TEXT,
  text TEXT,
  hour INTEGER,
  minute INTEGER,
  type_raw TEXT,
  is_active BOOLEAN,
  icon_name TEXT,
  color_hex TEXT,
  created_at TIMESTAMPTZ,
  sort_order INTEGER,
  report_data_type TEXT,
  report_day_preference TEXT,
  weekdays_raw TEXT[],
  field_hlcs JSONB,
  hlc TEXT NOT NULL,
  deleted BOOLEAN NOT NULL DEFAULT false,
  deleted_hlc TEXT,
  server_seq BIGINT NOT NULL,
  schema_version INTEGER NOT NULL DEFAULT 1,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  PRIMARY KEY (user_id, sync_id),
  CONSTRAINT notification_items_report_data_type_chk CHECK (report_data_type IS NULL OR report_data_type IN ('balance','expenses','income','topCategory')),
  CONSTRAINT notification_items_report_day_pref_chk CHECK (report_day_preference IS NULL OR report_day_preference IN ('sunday','monday','lastDay','firstDay'))
);

CREATE TABLE scheduled_payments (
  user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  sync_id UUID NOT NULL,
  name TEXT,
  note TEXT,
  amount NUMERIC(18,4),
  currency_code TEXT,
  is_variable_amount BOOLEAN,
  transaction_type TEXT,
  account_ref UUID,
  subcategory_ref UUID,
  tag_refs UUID[],
  need_override TEXT,
  is_recurring BOOLEAN,
  recurrence_type TEXT,
  recurrence_interval INTEGER,
  next_due_date TIMESTAMPTZ,
  day_of_month INTEGER,
  selected_weekdays TEXT[],
  yearly_month INTEGER,
  yearly_day INTEGER,
  end_date TIMESTAMPTZ,
  payment_category TEXT,
  notify_on_due_date BOOLEAN,
  notify_days_before INTEGER,
  is_active BOOLEAN,
  created_at TIMESTAMPTZ,
  last_paid_date TIMESTAMPTZ,
  skipped_dates_raw TEXT[],
  group_zone_id TEXT,
  split_total_amount NUMERIC(18,4),
  split_type TEXT,
  split_participant_ids_raw TEXT,
  split_values_raw TEXT,
  field_hlcs JSONB,
  hlc TEXT NOT NULL,
  deleted BOOLEAN NOT NULL DEFAULT false,
  deleted_hlc TEXT,
  server_seq BIGINT NOT NULL,
  schema_version INTEGER NOT NULL DEFAULT 1,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  PRIMARY KEY (user_id, sync_id)
);

CREATE TABLE subcategories (
  user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  sync_id UUID NOT NULL,
  name TEXT,
  color_hex TEXT,
  is_default_seed BOOLEAN,
  is_visible BOOLEAN,
  sort_order INTEGER,
  nature_raw_value TEXT,
  icon_name TEXT,
  is_system BOOLEAN,
  category_ref UUID,
  field_hlcs JSONB,
  hlc TEXT NOT NULL,
  deleted BOOLEAN NOT NULL DEFAULT false,
  deleted_hlc TEXT,
  server_seq BIGINT NOT NULL,
  schema_version INTEGER NOT NULL DEFAULT 1,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  PRIMARY KEY (user_id, sync_id)
);

CREATE TABLE tags (
  user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  sync_id UUID NOT NULL,
  name TEXT,
  color_hex TEXT,
  icon_name TEXT,
  is_active BOOLEAN,
  created_at TIMESTAMPTZ,
  field_hlcs JSONB,
  hlc TEXT NOT NULL,
  deleted BOOLEAN NOT NULL DEFAULT false,
  deleted_hlc TEXT,
  server_seq BIGINT NOT NULL,
  schema_version INTEGER NOT NULL DEFAULT 1,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  PRIMARY KEY (user_id, sync_id)
);

CREATE TABLE tx_items (
  user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  sync_id UUID NOT NULL,
  date TIMESTAMPTZ,
  local_day DATE,
  amount NUMERIC(18,4),
  currency_code TEXT,
  note TEXT,
  category_ref UUID,
  subcategory_ref UUID,
  account_ref UUID,
  tag_refs UUID[],
  amount_in_preferred_currency NUMERIC(18,4),
  preferred_currency_code TEXT,
  exchange_rate NUMERIC(18,8),
  is_exchange_rate_provisional BOOLEAN,
  need_override TEXT,
  scheduled_payment_ref UUID,
  balance_adjustment_type TEXT,
  transfer_pair_id TEXT,
  split_expense_id TEXT,
  split_group_zone_id TEXT,
  split_settlement_id TEXT,
  split_total_amount NUMERIC(18,4),
  split_type TEXT,
  split_my_value NUMERIC(18,4),
  split_divisor NUMERIC(18,4),
  created_at TIMESTAMPTZ,
  field_hlcs JSONB,
  hlc TEXT NOT NULL,
  deleted BOOLEAN NOT NULL DEFAULT false,
  deleted_hlc TEXT,
  server_seq BIGINT NOT NULL,
  schema_version INTEGER NOT NULL DEFAULT 1,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  PRIMARY KEY (user_id, sync_id)
);

-- ============ #18 user_preferences (KV, syncable; PK on key; no field_hlcs/deleted/schema_version) ============
CREATE TABLE user_preferences (
  user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  key TEXT NOT NULL,
  value TEXT,
  hlc TEXT NOT NULL,
  server_seq BIGINT NOT NULL,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  PRIMARY KEY (user_id, key)
);   -- + stamp_server_seq trigger (17th on the axis)

-- ============ #17 attest_keys (identity, NOT syncable; logical form — real home is Cloudflare D1) ============
CREATE TABLE attest_keys (
  user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  key_id TEXT NOT NULL,
  public_key BYTEA,
  attestation_type TEXT NOT NULL DEFAULT 'app_attest',
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  last_seen_at TIMESTAMPTZ,
  PRIMARY KEY (user_id, key_id)
);
CREATE UNIQUE INDEX attest_keys_keyid_unique ON attest_keys (attestation_type, key_id);

-- ============ report_claims (A3 per-day server-side report dedup) ============
CREATE TABLE report_claims (
  user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  report_type TEXT NOT NULL,
  local_day DATE NOT NULL,
  claimed_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  PRIMARY KEY (user_id, report_type, local_day)
);
CREATE FUNCTION claim_report(p_report_type TEXT, p_local_day DATE) RETURNS boolean
  LANGUAGE plpgsql SECURITY INVOKER SET search_path = public AS $$
BEGIN INSERT INTO report_claims (user_id, report_type, local_day)
  VALUES ((select auth.uid()), p_report_type, p_local_day)
  ON CONFLICT (user_id, report_type, local_day) DO NOTHING; RETURN FOUND; END; $$;

-- ============ hlc01 future-HLC cap (applied to staging AND production 2026-10-07; qa/cloud/hlc01_cap_future_hlc.sql) ============
-- Every HLC stored in a synced table is capped to "now + 60 s" (clock_timestamp()) by a BEFORE INSERT OR UPDATE trigger
-- cap_future_hlc on the 17 tables below (the 5 Groups tables carry it too: supabase-groups-staging.ddl §10). Verified
-- after applying: 22 cap_future_hlc triggers, qa/cloud/hlc01-cap-staging-probe.sh 4/4. The one-off normalisation
-- (update ... set hlc = hlc) is data, not schema, and is not reproduced here. Rollback: qa/cloud/hlc01_rollback.sql.
-- Functions + revoke, verbatim from the migration:
-- ------------------------------------------------------------------------------------------- el margen, en un sitio
create or replace function public.hlc_cap_margin() returns interval
language sql immutable set search_path = public as
$$ select interval '60 seconds' $$;

-- El tope de AHORA: instante canónico de 24 chars (`YYYY-MM-DDTHH:MI:SS.MSZ`) de `clock_timestamp() + margen`.
create or replace function public.hlc_cap_instant() returns text
language sql volatile set search_path = public as
$$ select to_char((clock_timestamp() at time zone 'utc') + public.hlc_cap_margin(), 'YYYY-MM-DD"T"HH24:MI:SS.MS"Z"') $$;

-- --------------------------------------------------------------------------------------------- el valor acotado
-- Un c1 válido cuyo prefijo es igual al tope ordena por encima en "C" (46 chars > 24) y la rama de abajo devuelve
-- exactamente el mismo string.
create or replace function public.hlc_cap_value(p_hlc text, p_cap text) returns text
language sql immutable set search_path = public as
$$
  select case
    when p_hlc is null or p_hlc = '' then p_hlc
    when p_hlc !~ '^[0-9]{4}-[0-9]{2}-[0-9]{2}T[0-9]{2}:[0-9]{2}:[0-9]{2}\.[0-9]{3}Z-[0-9a-f]{4}-[0-9a-f]{16}$'
      then p_cap || '-0000-0000000000000000'
    when p_hlc collate "C" <= p_cap collate "C" then p_hlc
    else p_cap || substr(p_hlc, 25)
  end
$$;

-- ------------------------------------------------------------------------------------------ el parche de una fila
create or replace function public.hlc_cap_patch(p_row jsonb, p_cap text) returns jsonb
language plpgsql immutable set search_path = public as
$$
declare
  v_patch   jsonb := '{}'::jsonb;
  v_hlc     text;
  v_capped  text;
  v_fh      jsonb := p_row -> 'field_hlcs';
  v_new_fh  jsonb;
  v_max     text;
begin
  if p_row ? 'hlc' then
    v_hlc := p_row ->> 'hlc';
    v_capped := public.hlc_cap_value(v_hlc, p_cap);
    if v_capped is distinct from v_hlc then
      v_patch := v_patch || jsonb_build_object('hlc', v_capped);
    end if;
  end if;

  if p_row ? 'deleted_hlc' then
    v_capped := public.hlc_cap_value(p_row ->> 'deleted_hlc', p_cap);
    if v_capped is distinct from (p_row ->> 'deleted_hlc') then
      v_patch := v_patch || jsonb_build_object('deleted_hlc', v_capped);
    end if;
  end if;

  if v_fh is not null and jsonb_typeof(v_fh) = 'object' then
    select coalesce(jsonb_object_agg(e.key,
             case jsonb_typeof(e.value)
               when 'null'   then e.value
               when 'string' then to_jsonb(public.hlc_cap_value(e.value #>> '{}', p_cap))
               else to_jsonb(p_cap || '-0000-0000000000000000')
             end), '{}'::jsonb)
      into v_new_fh
      from jsonb_each(v_fh) e;
    if v_new_fh <> v_fh then
      v_patch := v_patch || jsonb_build_object('field_hlcs', v_new_fh);
      -- El `hlc` de fila nunca por debajo de una unidad: acotadas al mismo milisegundo, manda el contador.
      if p_row ? 'hlc' then
        select max(x collate "C") into v_max
          from (select coalesce(v_patch ->> 'hlc', v_hlc) as x
                union all
                select e.value #>> '{}' from jsonb_each(v_new_fh) e where jsonb_typeof(e.value) = 'string') u
         where x is not null;
        if v_max is distinct from v_hlc then
          v_patch := v_patch || jsonb_build_object('hlc', v_max);
        end if;
      end if;
    end if;
  end if;

  return v_patch;
end
$$;

-- ------------------------------------------------------------------------------------------------- el trigger
-- SECURITY DEFINER: solo calcula (no lee ni escribe tablas), y así las funciones de arriba pueden quedar sin EXECUTE para
-- los clientes. Genérico por jsonb: cada tabla tiene un subconjunto distinto de (hlc, deleted_hlc, field_hlcs), y
-- `jsonb_populate_record(new, patch)` solo toca las claves del parche (las columnas bytea cifradas no se re-castean).
create or replace function public.cap_future_hlc() returns trigger
language plpgsql security definer set search_path = public as
$$
declare
  v_patch jsonb := public.hlc_cap_patch(to_jsonb(new), public.hlc_cap_instant());
begin
  if v_patch <> '{}'::jsonb then
    new := jsonb_populate_record(new, v_patch);
  end if;
  return new;
end
$$;

-- Higiene (molde g12_02): ninguna se llama desde un cliente.
revoke all on function public.hlc_cap_margin(), public.hlc_cap_instant(), public.hlc_cap_value(text, text),
  public.hlc_cap_patch(jsonb, text), public.cap_future_hlc()
  from public, anon, authenticated;

-- Triggers (the migration's do $$ loop, expanded): 16 domain entities + user_preferences.
CREATE TRIGGER cap_future_hlc BEFORE INSERT OR UPDATE ON accounts FOR EACH ROW EXECUTE FUNCTION cap_future_hlc();
CREATE TRIGGER cap_future_hlc BEFORE INSERT OR UPDATE ON budgets FOR EACH ROW EXECUTE FUNCTION cap_future_hlc();
CREATE TRIGGER cap_future_hlc BEFORE INSERT OR UPDATE ON cashflow_lines FOR EACH ROW EXECUTE FUNCTION cap_future_hlc();
CREATE TRIGGER cap_future_hlc BEFORE INSERT OR UPDATE ON cashflow_overrides FOR EACH ROW EXECUTE FUNCTION cap_future_hlc();
CREATE TRIGGER cap_future_hlc BEFORE INSERT OR UPDATE ON cashflow_plans FOR EACH ROW EXECUTE FUNCTION cap_future_hlc();
CREATE TRIGGER cap_future_hlc BEFORE INSERT OR UPDATE ON categories FOR EACH ROW EXECUTE FUNCTION cap_future_hlc();
CREATE TRIGGER cap_future_hlc BEFORE INSERT OR UPDATE ON exchange_rates FOR EACH ROW EXECUTE FUNCTION cap_future_hlc();
CREATE TRIGGER cap_future_hlc BEFORE INSERT OR UPDATE ON favorite_payments FOR EACH ROW EXECUTE FUNCTION cap_future_hlc();
CREATE TRIGGER cap_future_hlc BEFORE INSERT OR UPDATE ON group_bridge_prefs FOR EACH ROW EXECUTE FUNCTION cap_future_hlc();
CREATE TRIGGER cap_future_hlc BEFORE INSERT OR UPDATE ON inbox_drafts FOR EACH ROW EXECUTE FUNCTION cap_future_hlc();
CREATE TRIGGER cap_future_hlc BEFORE INSERT OR UPDATE ON merchant_memory FOR EACH ROW EXECUTE FUNCTION cap_future_hlc();
CREATE TRIGGER cap_future_hlc BEFORE INSERT OR UPDATE ON notification_items FOR EACH ROW EXECUTE FUNCTION cap_future_hlc();
CREATE TRIGGER cap_future_hlc BEFORE INSERT OR UPDATE ON scheduled_payments FOR EACH ROW EXECUTE FUNCTION cap_future_hlc();
CREATE TRIGGER cap_future_hlc BEFORE INSERT OR UPDATE ON subcategories FOR EACH ROW EXECUTE FUNCTION cap_future_hlc();
CREATE TRIGGER cap_future_hlc BEFORE INSERT OR UPDATE ON tags FOR EACH ROW EXECUTE FUNCTION cap_future_hlc();
CREATE TRIGGER cap_future_hlc BEFORE INSERT OR UPDATE ON tx_items FOR EACH ROW EXECUTE FUNCTION cap_future_hlc();
CREATE TRIGGER cap_future_hlc BEFORE INSERT OR UPDATE ON user_preferences FOR EACH ROW EXECUTE FUNCTION cap_future_hlc();
